version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/ssl:/etc/ssl"
      - "./:/var/www"
      - "./docker/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    ports:
      - "8000:80"
      - "3000:443"
    environment:
      - NGINX_HOST=localhost
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    build: docker
    image: nanoninja/php-fpm:8.1
    restart: always
    volumes:
      - "./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./:/var/www"
      - "./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"

  composer:
    image: "composer"
    volumes:
      - "./:/app"
    command: install
  mysqldb:
    image: mysql:8.0.30
    container_name: mysql_container
    restart: always
    environment:
      - MYSQL_DATABASE=innowise
      - MYSQL_ROOT_PASSWORD=root0root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root0root
      - MYSQL_HOST=127.0.0.1
    ports:
      - "8989:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"